services:
  mongo:
    image: mongo:7
    container_name: todo_mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./Backend
      target: production
    container_name: todo_backend
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      target: production
    container_name: todo_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
